### PR TITLE
Link to a Fire Type

### PR DESCRIPTION
**Pull request by YaBoyWonder**
I linked my discord emote of the fire type so you can decide if you want more of them to look like so. I have more types, but I am just interested to see if you are going to need/want them or not.

### CODE REVIEW

**Comment by Martmists-GH** [comment]
I'm interested, but 

- Don't host them on Discord/bundle them?
- Get all types as listed in the same style.
- Get them in a style that looks a bit better.

**Comment by YaBoyWonder** [comment]
These are the images, not hosted via Discord + better format


Fire 
-
fire

https://raw.githubusercontent.com/YaBoyWonder/pokemon-random/master/types/Fire.png

Dragon
-
dragon

https://raw.githubusercontent.com/YaBoyWonder/pokemon-random/master/types/Dragon.png



Electric 
-
electric

https://raw.githubusercontent.com/YaBoyWonder/pokemon-random/master/types/Electric.png

Grass 
-
grass

 https://raw.githubusercontent.com/YaBoyWonder/pokemon-random/master/types/Grass.png

<br>

The rest of the types are available if desired.

**Comment by Martmists-GH** [comment]
hmm.... Can you show me screenshots of how this looks in the application itself?

**Comment by YaBoyWonder** [comment]
I am currently away from my desktop so I am unable to head home and run the application for a few days. But if you just run your project by using the raw images from my directory in your types.json file in your resources, you should be able to see the output of it. 

They are already in default of .png as seen in the images you chose from bulbagarden
<br>
**[Git of Images](https://github.com/YaBoyWonder/pokemon-random/tree/master/types)**

**Comment by Martmists-GH** [comment]
Closing due to lack of activity

**Pull request closed without merging**
